import Foundation

// MARK: - Pokémon Dex (Easter Egg Data)

enum PokemonDex {
    struct Entry {
        let number: Int
        let name: String
        let types: [String]
        let hp: Int
        let attack: Int
        let defense: Int
        let speed: Int
        let flavor: String
    }

    static func lookup(_ name: String) -> Entry? {
        entries[name.lowercased()]
    }

    /// Load the sprite ANSI art from bundled resources. Returns nil if not found.
    static func sprite(for number: Int) -> String? {
        let filename = String(format: "%03d", number)
        guard let url = Bundle.main.url(forResource: filename, withExtension: "txt", subdirectory: "pokemon-sprites"),
              let data = try? Data(contentsOf: url),
              let text = String(data: data, encoding: .utf8)
        else { return nil }
        return text
    }

    // MARK: - Gen 1 Pokédex (151 entries)

    // swiftlint:disable function_body_length

    private static let entries: [String: Entry] = {
        // (number, name, types, hp, atk, def, spd, flavor)
        let data: [(Int, String, [String], Int, Int, Int, Int, String)] = [
            (1, "Bulbasaur", ["Grass", "Poison"], 45, 49, 49, 45,
             "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon."),
            (2, "Ivysaur", ["Grass", "Poison"], 60, 62, 63, 60,
             "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."),
            (3, "Venusaur", ["Grass", "Poison"], 80, 82, 83, 80,
             "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."),
            (4, "Charmander", ["Fire"], 39, 52, 43, 65,
             "The flame on its tail shows the strength of its life force. If it is weak, the flame also burns weakly."),
            (5, "Charmeleon", ["Fire"], 58, 64, 58, 80,
             "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws."),
            (6, "Charizard", ["Fire", "Flying"], 78, 84, 78, 100,
             "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames."),
            (7, "Squirtle", ["Water"], 44, 48, 65, 43,
             "When it retracts its long neck into its shell, it squirts out water with vigorous force."),
            (8, "Wartortle", ["Water"], 59, 63, 80, 58,
             "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old."),
            (9, "Blastoise", ["Water"], 79, 83, 100, 78,
             "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell."),
            (10, "Caterpie", ["Bug"], 45, 30, 35, 45,
             "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."),
            (11, "Metapod", ["Bug"], 50, 20, 55, 30,
             "It is vulnerable to attack while its shell is soft, exposing its weak and tender body."),
            (12, "Butterfree", ["Bug", "Flying"], 60, 45, 50, 70,
             "It loves the honey of flowers and can search out flower patches that have even tiny amounts of pollen."),
            (13, "Weedle", ["Bug", "Poison"], 40, 35, 30, 50,
             "It eats its weight in leaves every day. It fends off attackers with the needle on its head."),
            (14, "Kakuna", ["Bug", "Poison"], 45, 25, 50, 35,
             "While awaiting evolution, it hides from predators under leaves and in nooks of branches."),
            (15, "Beedrill", ["Bug", "Poison"], 65, 90, 40, 75,
             "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."),
            (16, "Pidgey", ["Normal", "Flying"], 40, 45, 40, 56,
             "It is docile and prefers to avoid conflict. If disturbed, however, it can ferociously strike back."),
            (17, "Pidgeotto", ["Normal", "Flying"], 63, 60, 55, 71,
             "It renders its prey immobile using well-developed claws, then carries it more than 60 miles to its nest."),
            (18, "Pidgeot", ["Normal", "Flying"], 83, 80, 75, 101,
             "By flapping its wings with all its might, it can make a gust of wind capable of bending tall trees."),
            (19, "Rattata", ["Normal"], 30, 56, 35, 72,
             "Cautious in the extreme, its hardy vitality lets it live in any kind of environment."),
            (20, "Raticate", ["Normal"], 55, 81, 60, 97,
             "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey."),
            (21, "Spearow", ["Normal", "Flying"], 40, 60, 30, 70,
             "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey."),
            (22, "Fearow", ["Normal", "Flying"], 65, 90, 65, 100,
             "It has the stamina to fly all day on its broad wings. It fights by using its sharp beak."),
            (23, "Ekans", ["Poison"], 35, 60, 44, 55,
             "It can freely detach its jaw to swallow large prey whole. It can become too heavy to move, however."),
            (24, "Arbok", ["Poison"], 60, 95, 69, 80,
             "The pattern on its belly appears to be a frightening face. Weak foes will flee just at the sight of it."),
            (25, "Pikachu", ["Electric"], 35, 55, 40, 90,
             "When several of these Pokémon gather, their electricity can build and cause lightning storms."),
            (26, "Raichu", ["Electric"], 60, 90, 55, 110,
             "Its long tail serves as a ground to protect itself from its own high-voltage power."),
            (27, "Sandshrew", ["Ground"], 50, 75, 85, 40,
             "It burrows and lives underground. If threatened, it curls itself up into a ball for protection."),
            (28, "Sandslash", ["Ground"], 75, 100, 110, 65,
             "It curls up, then rolls into foes with its back. Its sharp spines inflict severe damage."),
            (29, "Nidoran-F", ["Poison"], 55, 47, 52, 41,
             "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns."),
            (30, "Nidorina", ["Poison"], 70, 62, 67, 56,
             "The female has a gentle temperament. It emits ultrasonic cries that have the power to befuddle foes."),
            (31, "Nidoqueen", ["Poison", "Ground"], 90, 92, 87, 76,
             "Its body is covered in needle-like scales. It charges with its hefty body to knock foes flying."),
            (32, "Nidoran-M", ["Poison"], 46, 57, 40, 50,
             "It stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."),
            (33, "Nidorino", ["Poison"], 61, 72, 57, 65,
             "It has a violent disposition and stabs foes with its horn, which oozes poison upon impact."),
            (34, "Nidoking", ["Poison", "Ground"], 81, 102, 77, 85,
             "One swing of its mighty tail can snap a telephone pole as if it were a matchstick."),
            (35, "Clefairy", ["Fairy"], 70, 45, 48, 35,
             "Its adorable behavior and cry make it highly popular. However, this cute Pokémon is rarely found."),
            (36, "Clefable", ["Fairy"], 95, 70, 73, 60,
             "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people."),
            (37, "Vulpix", ["Fire"], 38, 41, 40, 65,
             "At the time of its birth, it has just one tail. The tail splits from the tip as it grows older."),
            (38, "Ninetales", ["Fire"], 73, 76, 75, 100,
             "Very smart and very vengeful. Grabbing one of its many tails could result in a 1,000-year curse."),
            (39, "Jigglypuff", ["Normal", "Fairy"], 115, 45, 20, 20,
             "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."),
            (40, "Wigglytuff", ["Normal", "Fairy"], 140, 70, 45, 45,
             "Its body is very elastic. By inhaling deeply, it can continue to inflate itself without limit."),
            (41, "Zubat", ["Poison", "Flying"], 40, 45, 35, 55,
             "It does not need eyes because it emits ultrasonic waves to check its surroundings while it flies."),
            (42, "Golbat", ["Poison", "Flying"], 75, 80, 70, 90,
             "It attacks in a stealthy manner, without warning. Its sharp fangs are used to bite and suck blood."),
            (43, "Oddish", ["Grass", "Poison"], 45, 50, 55, 30,
             "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds."),
            (44, "Gloom", ["Grass", "Poison"], 60, 65, 70, 40,
             "The honey it drools from its mouth smells so atrocious, it can curl noses at over a mile."),
            (45, "Vileplume", ["Grass", "Poison"], 75, 80, 85, 50,
             "It has the world's largest petals. With every step, the petals shake out heavy clouds of toxic pollen."),
            (46, "Paras", ["Bug", "Grass"], 35, 70, 55, 25,
             "Mushrooms named tochukaso grow on its back. They grow along with the host Paras."),
            (47, "Parasect", ["Bug", "Grass"], 60, 95, 80, 30,
             "A host-Loss parasite mushroom pair. The mushroom appears to do all the thinking."),
            (48, "Venonat", ["Bug", "Poison"], 60, 55, 50, 45,
             "Its large eyes act as radar. In pitch darkness, they will spot and zero in on its prey."),
            (49, "Venomoth", ["Bug", "Poison"], 70, 65, 60, 90,
             "The dust-like scales covering its wings are color-coded to indicate the kinds of poison it has."),
            (50, "Diglett", ["Ground"], 10, 55, 25, 95,
             "It prefers dark places. It spends most of its time underground, though it may pop up in caves."),
            (51, "Dugtrio", ["Ground"], 35, 100, 50, 120,
             "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground."),
            (52, "Meowth", ["Normal"], 40, 45, 35, 90,
             "It is nocturnal in nature. If it spots something shiny, its eyes glitter brightly."),
            (53, "Persian", ["Normal"], 65, 70, 60, 115,
             "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."),
            (54, "Psyduck", ["Water"], 50, 52, 48, 55,
             "It is constantly wracked by a headache. When the headache turns intense, it begins using mysterious powers."),
            (55, "Golduck", ["Water"], 80, 82, 78, 85,
             "It is seen swimming dynamically and elegantly using its well-developed limbs and flippers."),
            (56, "Mankey", ["Fighting"], 40, 80, 35, 70,
             "An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything."),
            (57, "Primeape", ["Fighting"], 65, 105, 60, 95,
             "It stops being angry only when nobody else is around. To view this moment is very difficult."),
            (58, "Growlithe", ["Fire"], 55, 70, 45, 60,
             "Very protective of its territory. It will bark and bite to repel intruders from its space."),
            (59, "Arcanine", ["Fire"], 90, 110, 80, 95,
             "A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings."),
            (60, "Poliwag", ["Water"], 40, 50, 40, 90,
             "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand."),
            (61, "Poliwhirl", ["Water"], 65, 65, 65, 90,
             "Capable of living in or out of water. When out of water, it sweats to keep its body slimy."),
            (62, "Poliwrath", ["Water", "Fighting"], 90, 95, 95, 70,
             "An adept swimmer at both the front crawl and breaststroke. Easily overtakes the best human swimmers."),
            (63, "Abra", ["Psychic"], 25, 20, 15, 90,
             "It sleeps for 18 hours a day. It uses a variety of extrasensory powers even while asleep."),
            (64, "Kadabra", ["Psychic"], 40, 35, 30, 105,
             "It emits special alpha waves from its body that induce headaches just by being close by."),
            (65, "Alakazam", ["Psychic"], 55, 50, 45, 120,
             "Its brain can outperform a supercomputer. Its IQ is said to be around 5,000."),
            (66, "Machop", ["Fighting"], 70, 80, 50, 35,
             "Its whole body is composed of muscles. Even though it is the size of a human child, it can hurl 100 adults."),
            (67, "Machoke", ["Fighting"], 80, 100, 70, 45,
             "It happily carries heavy cargo to toughen up. It willingly does hard work for people."),
            (68, "Machamp", ["Fighting"], 90, 130, 80, 55,
             "It punches with its four arms at blinding speed. It can launch 1,000 punches in two seconds."),
            (69, "Bellsprout", ["Grass", "Poison"], 50, 75, 35, 40,
             "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture."),
            (70, "Weepinbell", ["Grass", "Poison"], 65, 90, 50, 55,
             "It spits out PoisonPowder to immobilize the enemy and then finishes it with a spray of Acid."),
            (71, "Victreebel", ["Grass", "Poison"], 80, 105, 65, 70,
             "Said to live in huge colonies deep in jungles, although no one has ever returned from there."),
            (72, "Tentacool", ["Water", "Poison"], 40, 40, 35, 70,
             "It drifts in shallow seas. Anglers who hook them by accident are often stung by its toxic tentacles."),
            (73, "Tentacruel", ["Water", "Poison"], 80, 70, 65, 100,
             "Its 80 tentacles can stretch and contract freely. They wrap around prey and weaken it with poison."),
            (74, "Geodude", ["Rock", "Ground"], 40, 80, 100, 20,
             "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them."),
            (75, "Graveler", ["Rock", "Ground"], 55, 95, 115, 35,
             "It rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."),
            (76, "Golem", ["Rock", "Ground"], 80, 120, 130, 45,
             "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."),
            (77, "Ponyta", ["Fire"], 50, 85, 55, 90,
             "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in moments."),
            (78, "Rapidash", ["Fire"], 65, 100, 70, 105,
             "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it."),
            (79, "Slowpoke", ["Water", "Psychic"], 90, 65, 65, 15,
             "It is always vacantly lost in thought, but no one knows what it is thinking about."),
            (80, "Slowbro", ["Water", "Psychic"], 95, 75, 110, 30,
             "The Shellder that is latched onto its tail is said to feed on the host's leftover scraps."),
            (81, "Magnemite", ["Electric", "Steel"], 25, 35, 70, 45,
             "The units at the sides of its body generate antigravity energy to keep it aloft in the air."),
            (82, "Magneton", ["Electric", "Steel"], 50, 60, 95, 70,
             "It is actually three Magnemite linked by magnetism. It generates powerful radio waves."),
            (83, "Farfetchd", ["Normal", "Flying"], 52, 90, 55, 60,
             "It can't live without the stalk it holds. That's why it defends the stalk from attackers with its life."),
            (84, "Doduo", ["Normal", "Flying"], 35, 85, 45, 75,
             "A bird that makes up for its poor flying with its fast foot speed. It leaves giant footprints."),
            (85, "Dodrio", ["Normal", "Flying"], 60, 110, 70, 110,
             "Watch out if Dodrio's three heads are looking in three separate directions. It means they're on guard."),
            (86, "Seel", ["Water"], 65, 45, 55, 45,
             "The protruding horn on its head is very hard. It is used for bashing through thick ice."),
            (87, "Dewgong", ["Water", "Ice"], 90, 70, 80, 70,
             "Its streamlined body has little drag in water. The colder the temperature, the friskier it gets."),
            (88, "Grimer", ["Poison"], 80, 80, 50, 25,
             "Born from sludge, these Pokémon now inhabit only the filthiest of rivers."),
            (89, "Muk", ["Poison"], 105, 105, 75, 50,
             "A toxic fluid seeps from its body. The fluid instantly kills plants and trees on contact."),
            (90, "Shellder", ["Water"], 30, 65, 100, 40,
             "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."),
            (91, "Cloyster", ["Water", "Ice"], 50, 95, 180, 70,
             "When attacked, it launches its horns in quick volleys. Its innards have never been seen."),
            (92, "Gastly", ["Ghost", "Poison"], 30, 35, 30, 80,
             "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison."),
            (93, "Haunter", ["Ghost", "Poison"], 45, 50, 45, 95,
             "Its tongue is made of gas. If licked, its victim starts shaking constantly until death comes."),
            (94, "Gengar", ["Ghost", "Poison"], 60, 65, 60, 110,
             "To steal the life of its target, it slips into the prey's shadow and silently waits for an opportunity."),
            (95, "Onix", ["Rock", "Ground"], 35, 45, 160, 70,
             "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black."),
            (96, "Drowzee", ["Psychic"], 60, 48, 45, 42,
             "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."),
            (97, "Hypno", ["Psychic"], 85, 73, 70, 67,
             "It carries a pendulum-like device. There once was an incident in which it took away a child it hypnotized."),
            (98, "Krabby", ["Water"], 30, 105, 90, 50,
             "Its pincers are not only powerful weapons, they are used for balance when walking sideways."),
            (99, "Kingler", ["Water"], 55, 130, 115, 75,
             "The large pincer has 10,000-horsepower strength. However, being so big, it is unwieldy to use."),
            (100, "Voltorb", ["Electric"], 40, 30, 50, 100,
             "It was discovered when Poké Balls were introduced. It is said that there is some connection."),
            (101, "Electrode", ["Electric"], 60, 50, 70, 150,
             "It stores electric energy under very high pressure. It often explodes with little or no provocation."),
            (102, "Exeggcute", ["Grass", "Psychic"], 60, 40, 80, 40,
             "Even though it appears to be eggs, it was discovered to be closer to plant seeds."),
            (103, "Exeggutor", ["Grass", "Psychic"], 95, 95, 85, 55,
             "Its three heads think independently. However, they are friendly and never appear to squabble."),
            (104, "Cubone", ["Ground"], 50, 50, 95, 35,
             "It pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries."),
            (105, "Marowak", ["Ground"], 60, 80, 110, 45,
             "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."),
            (106, "Hitmonlee", ["Fighting"], 50, 120, 53, 87,
             "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides."),
            (107, "Hitmonchan", ["Fighting"], 50, 105, 79, 76,
             "Its punches slice the air. They are launched at such high speed, even a slight graze could cause a burn."),
            (108, "Lickitung", ["Normal"], 90, 55, 75, 30,
             "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."),
            (109, "Koffing", ["Poison"], 40, 65, 95, 35,
             "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."),
            (110, "Weezing", ["Poison"], 65, 90, 120, 60,
             "Where two kinds of poison gases meet, two Koffings can fuse into a Weezing over many years."),
            (111, "Rhyhorn", ["Ground", "Rock"], 80, 85, 95, 25,
             "It is inept at turning because of its four short legs. It can only charge and run in one direction."),
            (112, "Rhydon", ["Ground", "Rock"], 105, 130, 120, 40,
             "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees Fahrenheit."),
            (113, "Chansey", ["Normal"], 250, 5, 5, 50,
             "A kindly Pokémon that lays highly nutritious eggs and shares them with injured Pokémon or people."),
            (114, "Tangela", ["Grass"], 65, 55, 115, 60,
             "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks."),
            (115, "Kangaskhan", ["Normal"], 105, 95, 80, 90,
             "If you come across a young Kangaskhan playing by itself, never disturb it or attempt to catch it."),
            (116, "Horsea", ["Water"], 30, 40, 70, 60,
             "It makes its nest in the shade of corals. If it senses danger, it spits murky ink and flees."),
            (117, "Seadra", ["Water"], 55, 65, 95, 85,
             "It is capable of swimming backwards by rapidly flapping its fins and stinger at high speed."),
            (118, "Goldeen", ["Water"], 45, 67, 60, 63,
             "It swims at a steady 5 knots. If it senses danger, it will strike back with its sharp horn."),
            (119, "Seaking", ["Water"], 80, 92, 65, 68,
             "In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors."),
            (120, "Staryu", ["Water"], 30, 45, 55, 85,
             "An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle."),
            (121, "Starmie", ["Water", "Psychic"], 60, 75, 85, 115,
             "Its central core glows with the seven colors of the rainbow. Some people value it as a gem."),
            (122, "Mr. Mime", ["Psychic", "Fairy"], 40, 45, 65, 90,
             "It is adept at conning people. It is said to be able to create walls out of thin air by miming."),
            (123, "Scyther", ["Bug", "Flying"], 70, 110, 80, 105,
             "It slashes through grass with its sharp scythes, moving too fast for the human eye to track."),
            (124, "Jynx", ["Ice", "Psychic"], 65, 50, 35, 95,
             "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."),
            (125, "Electabuzz", ["Electric"], 65, 83, 57, 105,
             "Normally found near power plants, it can wander away and cause major blackouts in cities."),
            (126, "Magmar", ["Fire"], 65, 95, 57, 93,
             "Its body always burns with an orange glow that enables it to hide perfectly among flames."),
            (127, "Pinsir", ["Bug"], 65, 125, 100, 85,
             "It grips prey with its pincers until the prey is torn in half. What it can't tear, it tosses far."),
            (128, "Tauros", ["Normal"], 75, 100, 95, 110,
             "When it targets an enemy, it charges furiously while whipping its body with its long tails."),
            (129, "Magikarp", ["Water"], 20, 10, 55, 80,
             "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today."),
            (130, "Gyarados", ["Water", "Flying"], 95, 125, 79, 81,
             "Once it begins to rampage, a Gyarados will burn everything down, even in a harsh storm."),
            (131, "Lapras", ["Water", "Ice"], 130, 85, 80, 60,
             "A gentle soul that can read the minds of people. It can ferry people across the sea on its back."),
            (132, "Ditto", ["Normal"], 48, 48, 48, 48,
             "It can freely recombine its own cellular structure to transform into other life-forms."),
            (133, "Eevee", ["Normal"], 55, 55, 50, 55,
             "Its genetic code is irregular. It may mutate if exposed to radiation from elemental stones."),
            (134, "Vaporeon", ["Water"], 130, 65, 60, 65,
             "It lives close to water. Its long tail is ridged with a fin, which is often mistaken for a mermaid's."),
            (135, "Jolteon", ["Electric"], 65, 65, 60, 130,
             "It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts."),
            (136, "Flareon", ["Fire"], 65, 130, 60, 65,
             "It stores some of the air it inhales in its internal flame sac, which heats to over 3,000 degrees."),
            (137, "Porygon", ["Normal"], 65, 60, 70, 40,
             "A man-made Pokémon created using advanced scientific means. It can move freely in cyberspace."),
            (138, "Omanyte", ["Rock", "Water"], 35, 40, 100, 35,
             "A Pokémon that was resurrected from a fossil using modern science. It swam in ancient seas."),
            (139, "Omastar", ["Rock", "Water"], 70, 60, 125, 55,
             "A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey."),
            (140, "Kabuto", ["Rock", "Water"], 30, 80, 90, 55,
             "A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago."),
            (141, "Kabutops", ["Rock", "Water"], 60, 115, 105, 80,
             "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids."),
            (142, "Aerodactyl", ["Rock", "Flying"], 80, 105, 65, 130,
             "A ferocious Pokémon from the age of dinosaurs. It is imagined to have flown through open skies."),
            (143, "Snorlax", ["Normal"], 160, 110, 65, 30,
             "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."),
            (144, "Articuno", ["Ice", "Flying"], 90, 85, 100, 85,
             "A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains."),
            (145, "Zapdos", ["Electric", "Flying"], 90, 90, 85, 100,
             "A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts."),
            (146, "Moltres", ["Fire", "Flying"], 90, 100, 90, 90,
             "A legendary bird Pokémon. It is said that its appearance indicates the coming of spring."),
            (147, "Dratini", ["Dragon"], 41, 64, 45, 50,
             "Long considered a mythical Pokémon until recently when a small colony was found living underwater."),
            (148, "Dragonair", ["Dragon"], 61, 84, 65, 70,
             "A mystical Pokémon that exudes a gentle aura. It is said to have the ability to change the weather."),
            (149, "Dragonite", ["Dragon", "Flying"], 91, 134, 95, 80,
             "It is said to make its home somewhere in the sea. It guides crews of shipwrecks to shore."),
            (150, "Mewtwo", ["Psychic"], 106, 110, 90, 130,
             "It was created by a scientist after years of horrific gene-splicing and DNA-engineering experiments."),
            (151, "Mew", ["Psychic"], 100, 100, 100, 100,
             "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.")
        ]

        var dict: [String: Entry] = [:]
        for item in data {
            let entry = Entry(
                number: item.0, name: item.1, types: item.2,
                hp: item.3, attack: item.4, defense: item.5, speed: item.6,
                flavor: item.7
            )
            let key = item.1.lowercased()
            dict[key] = entry
            // Add alternate keys for names with special characters
            let altKey = key.replacingOccurrences(of: ". ", with: "-")
                .replacingOccurrences(of: "'", with: "")
            if altKey != key {
                dict[altKey] = entry
            }
        }
        return dict
    }()
    // swiftlint:enable function_body_length
}
