name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install developer tools
        run: brew install xcodegen swiftformat swiftlint

      - name: Run verification
        run: make can-release
